{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 4, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "       ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n       urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n       botocore.exceptions.SSLError: SSL validation failed for https://test-bucket.s3.amazonaws.com/context/9d9595c5d94fb65b824f56e9999527dba9542481580d69feb89056aabaa0aa87/content [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n", "test_name": "test_create_context", "rerun": "0"}, "1": {"status": "FAIL", "message": "       ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n       urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n       botocore.exceptions.SSLError: SSL validation failed for https://test-bucket.s3.amazonaws.com/context/9d9595c5d94fb65b824f56e9999527dba9542481580d69feb89056aabaa0aa87/content [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n", "test_name": "test_list_contexts", "rerun": "0"}, "2": {"status": "FAIL", "message": "       ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n       urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n       botocore.exceptions.SSLError: SSL validation failed for https://test-bucket.s3.amazonaws.com/context/9d9595c5d94fb65b824f56e9999527dba9542481580d69feb89056aabaa0aa87/content [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n", "test_name": "test_get_context", "rerun": "0"}, "3": {"status": "FAIL", "message": "       ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n       urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n       botocore.exceptions.SSLError: SSL validation failed for https://test-bucket.s3.amazonaws.com/context/9d9595c5d94fb65b824f56e9999527dba9542481580d69feb89056aabaa0aa87/content [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)\n", "test_name": "test_delete_context", "rerun": "0"}}, "suite_name": "tests/test_context.py"}}}, "date": "April 02, 2025", "start_time": 1743596823.903857, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "4", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "4"}